<a href="https://colab.research.google.com/github/prasad2154/NewVision/blob/main/pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Assignment 1 on *Dmart*
# Q. Select item_name,qty
# Q. Select last 3 columns using loc and iloc
# Q. Display min,max,average price
# Q. Display 1st and last column
# Q. Select middle 3 columns and first 3 rows.
# Q. Select last 2 rows and all columns
# Q. Display total amount

In [3]:
import pandas as pd
# create first D-Mart dataframe
data = {'id':[1,2,3,4,5],'item_name':['Rice 5kg Bag',
'Detergent Powder','Cooking Oil 1L', 'Biscuit Pack',
'Toothpaste'],'Price':[300,200,150,30,50],'Qty':[1,5,3,2,5],'Amount':[300,1000,450,60,250]}

In [4]:
df=pd.DataFrame(data)
df

   id         item_name  Price  Qty  Amount
0   1      Rice 5kg Bag    300    1     300
1   2  Detergent Powder    200    5    1000
2   3    Cooking Oil 1L    150    3     450
3   4      Biscuit Pack     30    2      60
4   5        Toothpaste     50    5     250

In [5]:
# Q. Select item_name,qty
df[['item_name','Qty']]

          item_name  Qty
0      Rice 5kg Bag    1
1  Detergent Powder    5
2    Cooking Oil 1L    3
3      Biscuit Pack    2
4        Toothpaste    5

In [7]:
# Q. Select last 3 columns using loc and iloc
df.iloc[:,2:]

   Price  Qty  Amount
0    300    1     300
1    200    5    1000
2    150    3     450
3     30    2      60
4     50    5     250

In [10]:
df.loc[:,['Price','Qty','Amount']]

   Price  Qty  Amount
0    300    1     300
1    200    5    1000
2    150    3     450
3     30    2      60
4     50    5     250

In [11]:
# Q. Display min,max,average price
df['Price'].max()

300

In [12]:
df['Price'].min()

30

In [15]:
print(df['Price'].mean())

146.0

In [16]:
# Display first and last column
df[['id',"Amount"]]  #method 1

   id  Amount
0   1     300
1   2    1000
2   3     450
3   4      60
4   5     250

In [21]:
# method 2
df.iloc[:,::4]

   id  Amount
0   1     300
1   2    1000
2   3     450
3   4      60
4   5     250

In [22]:
df

   id         item_name  Price  Qty  Amount
0   1      Rice 5kg Bag    300    1     300
1   2  Detergent Powder    200    5    1000
2   3    Cooking Oil 1L    150    3     450
3   4      Biscuit Pack     30    2      60
4   5        Toothpaste     50    5     250

In [23]:
# Q. Select middle 3 columns and first 3 rows.

df.iloc[:3,1:4]

          item_name  Price  Qty
0      Rice 5kg Bag    300    1
1  Detergent Powder    200    5
2    Cooking Oil 1L    150    3

In [27]:
# method 2
df.loc[:3,"item_name":"Qty"]

          item_name  Price  Qty
0      Rice 5kg Bag    300    1
1  Detergent Powder    200    5
2    Cooking Oil 1L    150    3
3      Biscuit Pack     30    2

In [28]:
# Q. select last 2 rows and all columns
df.iloc[3:,:]

   id     item_name  Price  Qty  Amount
3   4  Biscuit Pack     30    2      60
4   5    Toothpaste     50    5     250

In [29]:
# Method 2
df.loc[3:,'id':'Amount']

   id     item_name  Price  Qty  Amount
3   4  Biscuit Pack     30    2      60
4   5    Toothpaste     50    5     250

In [30]:
# Display Total AmOUNT
df['Amount'].sum()

np.int64(2060)