<a href="https://colab.research.google.com/github/prasad2154/NewVision/blob/main/pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Assignment 1 on *Dmart*
# Q. Select item_name,qty
# Q. Select last 3 columns using loc and iloc
# Q. Display min,max,average price
# Q. Display 1st and last column
# Q. Select middle 3 columns and first 3 rows.
# Q. Select last 2 rows and all columns
# Q. Display total amount

In [2]:
import pandas as pd
# create first D-Mart dataframe
data = {'id':[1,2,3,4,5],'item_name':['Rice 5kg Bag',
'Detergent Powder','Cooking Oil 1L', 'Biscuit Pack',
'Toothpaste'],'Price':[300,200,150,30,50],'Qty':[1,5,3,2,5],'Amount':[300,1000,450,60,250]}

In [3]:
df=pd.DataFrame(data)
df

   id         item_name  Price  Qty  Amount
0   1      Rice 5kg Bag    300    1     300
1   2  Detergent Powder    200    5    1000
2   3    Cooking Oil 1L    150    3     450
3   4      Biscuit Pack     30    2      60
4   5        Toothpaste     50    5     250

In [4]:
# Q. Select item_name,qty
df[['item_name','Qty']]

          item_name  Qty
0      Rice 5kg Bag    1
1  Detergent Powder    5
2    Cooking Oil 1L    3
3      Biscuit Pack    2
4        Toothpaste    5

In [5]:
# Q. Select last 3 columns using loc and iloc
df.iloc[:,2:]

   Price  Qty  Amount
0    300    1     300
1    200    5    1000
2    150    3     450
3     30    2      60
4     50    5     250

In [6]:
df.loc[:,['Price','Qty','Amount']]

   Price  Qty  Amount
0    300    1     300
1    200    5    1000
2    150    3     450
3     30    2      60
4     50    5     250

In [7]:
# Q. Display min,max,average price
df['Price'].max()

300

In [8]:
df['Price'].min()

30

In [9]:
print(df['Price'].mean())

146.0

In [10]:
# Display first and last column
df[['id',"Amount"]]  #method 1

   id  Amount
0   1     300
1   2    1000
2   3     450
3   4      60
4   5     250

In [11]:
# method 2
df.iloc[:,::4]

   id  Amount
0   1     300
1   2    1000
2   3     450
3   4      60
4   5     250

In [12]:
df

   id         item_name  Price  Qty  Amount
0   1      Rice 5kg Bag    300    1     300
1   2  Detergent Powder    200    5    1000
2   3    Cooking Oil 1L    150    3     450
3   4      Biscuit Pack     30    2      60
4   5        Toothpaste     50    5     250

In [13]:
# Q. Select middle 3 columns and first 3 rows.

df.iloc[:3,1:4]

          item_name  Price  Qty
0      Rice 5kg Bag    300    1
1  Detergent Powder    200    5
2    Cooking Oil 1L    150    3

In [14]:
# method 2
df.loc[:3,"item_name":"Qty"]

          item_name  Price  Qty
0      Rice 5kg Bag    300    1
1  Detergent Powder    200    5
2    Cooking Oil 1L    150    3
3      Biscuit Pack     30    2

In [15]:
# Q. select last 2 rows and all columns
df.iloc[3:,:]

   id     item_name  Price  Qty  Amount
3   4  Biscuit Pack     30    2      60
4   5    Toothpaste     50    5     250

In [16]:
# Method 2
df.loc[3:,'id':'Amount']

   id     item_name  Price  Qty  Amount
3   4  Biscuit Pack     30    2      60
4   5    Toothpaste     50    5     250

In [17]:
# Display Total AmOUNT
df['Amount'].sum()

np.int64(2060)

Assignment 2
Create a DataFrame for a Library with at least 5 entries.

Columns: book_id | book_name | author | price | copies_sold

Q1. Select book_name and author.
Q2. Select the last 2 columns using loc and iloc.
Q3. Display the minimum, maximum, and average price of books.
Q4. Display the book_id|author|copies_sold
Q5. Select the middle 3 columns and the first 3 rows.
Q6. Select the last random 3 rows and all columns.
Q7. Display the total number of copies_sold.
Q8. Create a new column total_sales (calculated as price * copies_sold) and display the DataFrame.

In [ ]:


# Q1. Select book_name and author.
# Q2. Select the last 2 columns using loc and iloc.
# Q3. Display the minimum, maximum, and average price of books.
# Q4. Display the book_id|author|copies_sold
# Q5. Select the middle 3 columns and the first 3 rows.
# Q6. Select the last random 3 rows and all columns.
# Q7. Display the total number of copies_sold.
# # Q8. Create a new column total_sales (calculated as price * copies_sold) and display the DataFrame.

In [18]:
data={'book_id':[11,12,13,14,15],'book_name':["The God of Small Things",
    "Midnight's Children",
    "The White Tiger",
    "A Suitable Boy",
    "Train to Pakistan"],'author':["Arundhati Roy",
    "Salman Rushdie",
    "Aravind Adiga",
    "Vikram Seth",
    "Khushwant Singh"],'Price':[499, 599, 399, 699, 350],'copies_sold':[1200000, 850000, 750000, 1000000, 600000]}

In [19]:
df1=pd.DataFrame(data)
df1

   book_id                book_name           author  Price  copies_sold
0       11  The God of Small Things    Arundhati Roy    499      1200000
1       12      Midnight's Children   Salman Rushdie    599       850000
2       13          The White Tiger    Aravind Adiga    399       750000
3       14           A Suitable Boy      Vikram Seth    699      1000000
4       15        Train to Pakistan  Khushwant Singh    350       600000

In [24]:
# Q1. Select book_name and author.
df1[['book_name','author']]

                 book_name           author
0  The God of Small Things    Arundhati Roy
1      Midnight's Children   Salman Rushdie
2          The White Tiger    Aravind Adiga
3           A Suitable Boy      Vikram Seth
4        Train to Pakistan  Khushwant Singh

In [25]:
# Q2. Select the last 2 columns using loc and iloc.
df1.iloc[:,-2:]

   Price  copies_sold
0    499      1200000
1    599       850000
2    399       750000
3    699      1000000
4    350       600000

In [31]:
df1.loc[:,'Price':'copies_sold']

   Price  copies_sold
0    499      1200000
1    599       850000
2    399       750000
3    699      1000000
4    350       600000

In [32]:
# Q3. Display the minimum, maximum, and average price of books.
df1['Price'].max()

699

In [33]:
# Min
df1['Price'].min()

350

In [34]:
# Mean
print(df1['Price'].mean())

509.2

In [35]:
# Q4. Display the book_id|author|copies_sold
df1[['book_id','author','copies_sold']]

   book_id           author  copies_sold
0       11    Arundhati Roy      1200000
1       12   Salman Rushdie       850000
2       13    Aravind Adiga       750000
3       14      Vikram Seth      1000000
4       15  Khushwant Singh       600000

In [36]:
# Q5. Select the middle 3 columns and the first 3 rows.
df1.iloc[:3,1:4]

                 book_name          author  Price
0  The God of Small Things   Arundhati Roy    499
1      Midnight's Children  Salman Rushdie    599
2          The White Tiger   Aravind Adiga    399

In [37]:
# Q6. Select the last random 3 rows and all columns
df1.iloc[2:,:]

   book_id          book_name           author  Price  copies_sold
2       13    The White Tiger    Aravind Adiga    399       750000
3       14     A Suitable Boy      Vikram Seth    699      1000000
4       15  Train to Pakistan  Khushwant Singh    350       600000

In [39]:
# Q7. Display the total number of copies_sold.
print(df1['copies_sold'].sum())

4400000

In [40]:
# Q8. Create a new column total_sales (calculated as price * copies_sold) and display the DataFrame.

df1['total_sales']=df1['Price']*df1['copies_sold']
df1

,book_id,book_name,author,Price,copies_sold,total_sales
0,11,The God of Small Things,Arundhati Roy,499,1200000,598800000
1,12,Midnight's Children,Salman Rushdie,599,850000,509150000
2,13,The White Tiger,Aravind Adiga,399,750000,299250000
3,14,A Suitable Boy,Vikram Seth,699,1000000,699000000
4,15,Train to Pakistan,Khushwant Singh,350,600000,210000000