<a href="https://colab.research.google.com/github/prasad2154/NewVision/blob/main/Daily_Session_work/Day21_DS_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
path ="/content/CO2 Emissions_Canada.csv"
import pandas as pd
c=pd.read_csv(path)
c.head(10)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
5,ACURA,RLX,MID-SIZE,3.5,6,AS6,Z,11.9,7.7,10.0,28,230
6,ACURA,TL,MID-SIZE,3.5,6,AS6,Z,11.8,8.1,10.1,28,232
7,ACURA,TL AWD,MID-SIZE,3.7,6,AS6,Z,12.8,9.0,11.1,25,255
8,ACURA,TL AWD,MID-SIZE,3.7,6,M6,Z,13.4,9.5,11.6,24,267
9,ACURA,TSX,COMPACT,2.4,4,AS5,Z,10.6,7.5,9.2,31,212

In [13]:
c.columns

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)'],
      dtype='object')

**Filter based selection/conditional operation**

In [14]:
# Filter operation
c['Make'].unique()

array(['ACURA', 'ALFA ROMEO', 'ASTON MARTIN', 'AUDI', 'BENTLEY', 'BMW',
       'BUICK', 'CADILLAC', 'CHEVROLET', 'CHRYSLER', 'DODGE', 'FIAT',
       'FORD', 'GMC', 'HONDA', 'HYUNDAI', 'INFINITI', 'JAGUAR', 'JEEP',
       'KIA', 'LAMBORGHINI', 'LAND ROVER', 'LEXUS', 'LINCOLN', 'MASERATI',
       'MAZDA', 'MERCEDES-BENZ', 'MINI', 'MITSUBISHI', 'NISSAN',
       'PORSCHE', 'RAM', 'ROLLS-ROYCE', 'SCION', 'SMART', 'SRT', 'SUBARU',
       'TOYOTA', 'VOLKSWAGEN', 'VOLVO', 'GENESIS', 'BUGATTI'],
      dtype=object)

In [19]:
c.query("Make=='BMW'")

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
76,BMW,320i,COMPACT,2.0,4,A8,Z,10.0,6.5,8.4,34,193
77,BMW,320i,COMPACT,2.0,4,M6,Z,10.4,6.7,8.7,32,200
78,BMW,320i xDRIVE,COMPACT,2.0,4,A8,Z,10.2,7.0,8.8,32,202
79,BMW,328d xDRIVE,COMPACT,2.0,4,A8,D,7.6,5.5,6.7,42,181
80,BMW,328d xDRIVE TOURING,STATION WAGON - SMALL,2.0,4,A8,D,7.6,5.5,6.7,42,181
...,...,...,...,...,...,...,...,...,...,...,...,...
6635,BMW,X7 xDrive40i,SUV - STANDARD,3.0,6,AS8,Z,12.0,9.4,10.8,26,254
6636,BMW,X7 xDrive50i,SUV - STANDARD,4.4,8,AS8,Z,15.5,11.4,13.6,21,318
6637,BMW,X7 M50i,SUV - STANDARD,4.4,8,AS8,Z,15.5,11.4,13.6,21,318
6638,BMW,Z4 sDrive30i,TWO-SEATER,2.0,4,AS8,Z,9.5,7.4,8.5,33,200
6639,BMW,Z4 M40i,TWO-SEATER,3.0,6,AS8,Z,10.3,8.0,9.3,30,216

In [20]:
c.query("Make=='KIA'")

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
602,KIA,CADENZA,FULL-SIZE,3.3,6,A6,X,12.7,8.8,10.9,26,251
603,KIA,FORTE,MID-SIZE,1.8,4,A6,X,9.6,6.6,8.3,34,191
604,KIA,FORTE,MID-SIZE,1.8,4,M6,X,9.3,6.4,8.0,35,184
605,KIA,FORTE,MID-SIZE,2.0,4,A6,X,9.8,6.6,8.4,34,193
606,KIA,FORTE,MID-SIZE,2.0,4,M6,X,9.7,6.8,8.4,34,193
...,...,...,...,...,...,...,...,...,...,...,...,...
7053,KIA,Sportage,SUV - SMALL,2.4,4,AS6,X,10.1,7.6,9.0,31,214
7054,KIA,Sportage AWD,SUV - SMALL,2.0,4,AS6,X,12.1,9.6,11.0,26,261
7055,KIA,Sportage AWD,SUV - SMALL,2.4,4,AS6,X,10.8,9.1,10.0,28,239
7056,KIA,Stinger AWD,MID-SIZE,3.3,6,AS8,Z,13.6,9.6,11.8,24,279
7057,KIA,Telluride AWD,SUV - SMALL,3.8,6,AS8,X,12.5,9.6,11.2,25,264

In [21]:
c.query("Make=='BMW' and Cylinders >6")

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
103,BMW,550i xDRIVE,MID-SIZE,4.4,8,A8,Z,14.4,9.6,12.2,23,281
104,BMW,550i xDRIVE GRAN TURISMO,FULL-SIZE,4.4,8,A8,Z,15.0,9.8,12.7,22,292
106,BMW,650i xDRIVE CABRIOLET,SUBCOMPACT,4.4,8,A8,Z,15.0,9.8,12.7,22,292
107,BMW,650i xDRIVE COUPE,COMPACT,4.4,8,A8,Z,14.4,9.6,12.2,23,281
108,BMW,650i xDRIVE GRAN COUPE,COMPACT,4.4,8,A8,Z,15.0,9.8,12.7,22,292
...,...,...,...,...,...,...,...,...,...,...,...,...
6631,BMW,X5 xDrive50i,SUV - STANDARD,4.4,8,AS8,Z,14.5,10.7,12.8,22,302
6632,BMW,X5 M50i,SUV - STANDARD,4.4,8,AS8,Z,14.5,10.7,12.8,22,302
6634,BMW,X6 M50i,SUV - STANDARD,4.4,8,AS8,Z,14.5,10.7,12.8,22,302
6636,BMW,X7 xDrive50i,SUV - STANDARD,4.4,8,AS8,Z,15.5,11.4,13.6,21,318
6637,BMW,X7 M50i,SUV - STANDARD,4.4,8,AS8,Z,15.5,11.4,13.6,21,318