<a href="https://colab.research.google.com/github/prasad2154/NewVision/blob/main/Day19/20_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas Data Analysis**

In [ ]:
# In pandas we have 2 imp. data structures
# 1. Series - 1D data structure (rows)
# 2. DataFrame -  2D data structure (rows,columns)

# Q. What is the difference between Series and DataFrame???

# A Series is a one-dimensional array that can store a single column of data.

# Like a single column in Excel
# Has index + values
# Can store any data type (int, float, string, etc.)

# A DataFrame is a two-dimensional table made up of multiple Series.

# Like a full Excel table (rows + columns)
# Each column is a Series
# Can store different data types in different columns

In [ ]:
import pandas as pd

data = [120,30,40,55,11]
s=pd.Series(data)
print(s)

0    120
1     30
2     40
3     55
4     11
dtype: int64

In [ ]:
# lets create dataframe
df = pd.DataFrame([[10,20,30],[30,40,50],])
df

    0   1   2
0  10  20  30
1  30  40  50

In [ ]:
df = pd.DataFrame([[10,20,30],[30,40,50],[30,50]])
df

    0   1     2
0  10  20  30.0
1  30  40  50.0
2  30  50   NaN

In [ ]:
type(s)

pandas.core.series.Series

In [ ]:
df.ndim

2

In [ ]:
# Assignment:
# Try to create a series and Dataframe with str,tuple,list[list],list[tuple],set.dict

In [ ]:
path = "https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv"
df =pd.read_csv(path)
df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [ ]:
# display first 5 records
# df.head()   # default it returns 5 values
df.head(6)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
5,183277,E. Hazard,27,Belgium,91,91,Chelsea,93000.0,340.0,Right,4.0,4.0,LF,2012,2020-01-01,5.666667,163.0,172100.0

In [ ]:
df[:4]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0

In [ ]:
df[2:6]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
5,183277,E. Hazard,27,Belgium,91,91,Chelsea,93000.0,340.0,Right,4.0,4.0,LF,2012,2020-01-01,5.666667,163.0,172100.0

In [ ]:
# load last 3 record

df.tail(3)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [ ]:
# summary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        18207 non-null  int64
 1   Name                      18207 non-null  object
 2   Age                       18207 non-null  int64
 3   Nationality               18207 non-null  object
 4   Overall                   18207 non-null  int64
 5   Potential                 18207 non-null  int64
 6   Club                      17966 non-null  object
 7   Value                     17955 non-null  float64
 8   Wage                      18207 non-null  float64
 9   Preferred Foot            18207 non-null  object
 10  International Reputation  18159 non-null  float64
 11  Skill Moves               18159 non-null  float64
 12  Position                  18207 non-null  object
 13  Joined                    18207 non-null  int64
 14  Contract Valid Until      17918 non-null  object
 15  Height                    18207 non-null  float64
 16  Weight                    18207 non-null  float64
 17  Release Clause            18207 non-null  float64
dtypes: float64(7), int64(5), object(6)
memory usage: 2.5+ MB

In [ ]:
# Q. how to check missing values

df.isna().sum()/len(df)*100

ID                          0.000000
Name                        0.000000
Age                         0.000000
Nationality                 0.000000
Overall                     0.000000
Potential                   0.000000
Club                        1.323667
Value                       1.384083
Wage                        0.000000
Preferred Foot              0.000000
International Reputation    0.263635
Skill Moves                 0.263635
Position                    0.000000
Joined                      0.000000
Contract Valid Until        1.587302
Height                      0.000000
Weight                      0.000000
Release Clause              0.000000
dtype: float64

1000

10/8/20---> DELETE

250/400< ---> Handle

In [ ]:
df.isna().sum()

ID                            0
Name                          0
Age                           0
Nationality                   0
Overall                       0
Potential                     0
Club                        241
Value                       252
Wage                          0
Preferred Foot                0
International Reputation     48
Skill Moves                  48
Position                      0
Joined                        0
Contract Valid Until        289
Height                        0
Weight                        0
Release Clause                0
dtype: int64

In [ ]:
df.shape

(18207, 18)

In [ ]:
18207-17907

300

In [ ]:
# Lets drop the NaN
df.dropna().shape

(17907, 18)

In [ ]:
df.dropna(inplace = True)
df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [ ]:
# check missing values after dropna
df.isna().sum()

ID                          0
Name                        0
Age                         0
Nationality                 0
Overall                     0
Potential                   0
Club                        0
Value                       0
Wage                        0
Preferred Foot              0
International Reputation    0
Skill Moves                 0
Position                    0
Joined                      0
Contract Valid Until        0
Height                      0
Weight                      0
Release Clause              0
dtype: int64

In [ ]:
import numpy as np
a = np.array([10,20,30,np.nan])
a+100

array([110., 120., 130.,  nan])

In [ ]:
b =np.array( [10, 20, 30,np.nan])
b .mean()

np.float64(nan)

In [ ]:
# drop columns
df.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Preferred Foot', 'International Reputation',
       'Skill Moves', 'Position', 'Joined', 'Contract Valid Until', 'Height',
       'Weight', 'Release Clause'],
      dtype='object')

In [ ]:
df.drop(columns=['ID'],inplace=True)

In [ ]:
df.columns

Index(['Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club', 'Value',
       'Wage', 'Preferred Foot', 'International Reputation', 'Skill Moves',
       'Position', 'Joined', 'Contract Valid Until', 'Height', 'Weight',
       'Release Clause'],
      dtype='object')

In [ ]:
# assignment:  convert space to _
# ex. Preferred Foot --> Preferred_Foot

text = "Preferred Foot"

result = text.replace(" ", "_")

print(result)

Preferred_Foot

**Assignment**

In [ ]:
# Assignment:
# Try to create a series and Dataframe with str,tuple,list[list],list[tuple],set.dict

In [ ]:
# string

import pandas as pd
# series
s=pd.Series("Thursday")
print(s)
# Dataframe
df=pd.DataFrame(list("Thursday"),columns=["Characters"])
print("Dataframe:")
print(df)

0    Thursday
dtype: object
Dataframe:
  Characters
0          T
1          h
2          u
3          r
4          s
5          d
6          a
7          y

In [ ]:
# Tuple
# series
import pandas as pd
data = ("Python","Java","Html","CSS")
s=pd.Series(data)
print("series:")
print(s)

# Dataframe
df=pd.DataFrame(data,columns=["Programming Languages"])
print("\n DataFrame:")
print(df)

series:
0    Python
1      Java
2      Html
3       CSS
dtype: object

 DataFrame:
  Programming Languages
0                Python
1                  Java
2                  Html
3                   CSS

In [ ]:
# list

import pandas as pd

num = [121,144,169,196,225]

# series
s=pd.Series(num)
print("series:")
print(s)

# Dataframe
df=pd.DataFrame(num,columns=["Numbers"])
print("\n DataFrame:")
print(df)

series:
0    121
1    144
2    169
3    196
4    225
dtype: int64

 DataFrame:
   Numbers
0      121
1      144
2      169
3      196
4      225

In [ ]:
# From List of Lists
import pandas as pd

data = [
    ["Prasad", 22],
    ["Rahul", 25],
    ["Amit", 24]
]

# DataFrame
df = pd.DataFrame(data, columns=["Name", "Age"])
print(df)

# Series (First Row)
s = pd.Series(data[0])
print("\nSeries:")
print(s)

     Name  Age
0  Prasad   22
1   Rahul   25
2    Amit   24

Series:
0    Prasad
1        22
dtype: object

In [ ]:
# From List of Tuples
data = [
    ("Prasad", 24),
    ("Pranali", 25),
    ("Amit", 24)
]

# DataFrame
df = pd.DataFrame(data, columns=["Name", "Age"])
print(df)

# Series (First Tuple)
s = pd.Series(data[0])
print("\nSeries:")
print(s)

      Name  Age
0   Prasad   24
1  Pranali   25
2     Amit   24

Series:
0    Prasad
1        24
dtype: object

In [ ]:
# Set
import pandas as pd

data = {11, 21, 31, 41, 51}

# Series
s = pd.Series(list(data))
print("Series:")
print(s)

# DataFrame
df = pd.DataFrame(data, columns=["Numbers"])
print("\nDataFrame:")
print(df)

Series:
0    51
1    21
2    41
3    11
4    31
dtype: int64

DataFrame:
   Numbers
0       51
1       21
2       41
3       11
4       31

In [ ]:
# Dictionary

data = {
    "Name": "Prasad",
    "Age": 22,
    "City": "Pune"
}
# Series
s = pd.Series(data)
print("Series:")
print(s)

# DataFrame
df = pd.DataFrame([data])
print("\nDataFrame:")
print(df)

Series:
Name    Prasad
Age         22
City      Pune
dtype: object

DataFrame:
     Name  Age  City
0  Prasad   22  Pune

In [ ]:
# Dataframe using dict
# key beacomes a label(column names) of df

import pandas as pd
t = {'Num1':[1,2,3,4],'Num2':[6,7,8,9]}
pd.DataFrame(t)

   Num1  Num2
0     1     6
1     2     7
2     3     8
3     4     9

In [ ]:
t = {'Num1':[1,2,3,4],'Num2':[6,7,8,9]}
pd.Series(t)

Num1    [1, 2, 3, 4]
Num2    [6, 7, 8, 9]
dtype: object

In [ ]:
setData = {1,2,3,4,5,6,7,8,9,10}
pd.Series(list(setData))

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

# **Part** **2**

In [ ]:
path = "https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv"

df = pd.read_csv(path)

df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

# **Raw and column operations**

In [ ]:
# access single column
df["Nationality"]

0        Argentina
1         Portugal
2           Brazil
3            Spain
4          Belgium
           ...
18202      England
18203       Sweden
18204      England
18205      England
18206      England
Name: Nationality, Length: 18207, dtype: object

In [ ]:
df['International Reputation']

0        5.0
1        5.0
2        5.0
3        4.0
4        4.0
        ...
18202    1.0
18203    1.0
18204    1.0
18205    1.0
18206    1.0
Name: International Reputation, Length: 18207, dtype: float64

In [ ]:
# approch 2--->
df.Age  # but only access single word

0        31
1        33
2        26
3        27
4        27
         ..
18202    19
18203    19
18204    16
18205    17
18206    16
Name: Age, Length: 18207, dtype: int64

In [ ]:
# access more than 1 columns[[]]
df[["Age","Height","Club"]]

       Age    Height                 Club
0       31  5.583333         FC Barcelona
1       33  6.166667             Juventus
2       26  5.750000  Paris Saint-Germain
3       27  6.333333    Manchester United
4       27  5.916667      Manchester City
...    ...       ...                  ...
18202   19  5.750000      Crewe Alexandra
18203   19  6.250000       Trelleborgs FF
18204   16  5.666667     Cambridge United
18205   17  5.833333      Tranmere Rovers
18206   16  5.833333      Tranmere Rovers

[18207 rows x 3 columns]

In [ ]:
df[["Age","Height","Club"]]

NameError: name 'head' is not defined

In [ ]:
# to access rows and column we have 2 more options present in pandas
# loc--label based selection
# we can't use indexing in columns
# so we use labels.from which to which column data we need that range wise column label  we give for slicing

df.loc[:10,"Name":"Overall"]  #(rows,column)

                 Name  Age Nationality  Overall
0            L. Messi   31   Argentina       94
1   Cristiano Ronaldo   33    Portugal       94
2           Neymar Jr   26      Brazil       92
3              De Gea   27       Spain       91
4        K. De Bruyne   27     Belgium       91
5           E. Hazard   27     Belgium       91
6           L. Modrić   32     Croatia       91
7           L. Suárez   31     Uruguay       91
8        Sergio Ramos   32       Spain       91
9            J. Oblak   25    Slovenia       90
10     R. Lewandowski   29      Poland       90

In [ ]:
# in slicing we can acces sequncially i.e problem so we need unorder data. which important that only.so we use [] and give which columns we need
df.loc[:5,["Name","Club",'Nationality',"Age"]]

                Name                 Club Nationality  Age
0           L. Messi         FC Barcelona   Argentina   31
1  Cristiano Ronaldo             Juventus    Portugal   33
2          Neymar Jr  Paris Saint-Germain      Brazil   26
3             De Gea    Manchester United       Spain   27
4       K. De Bruyne      Manchester City     Belgium   27
5          E. Hazard              Chelsea     Belgium   27

In [ ]:
# iloc---index based selection
# stop is exclusive
#  diff loc vs iloc ????  in
df.iloc[:2,:]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0

In [ ]:
df.iloc[:-2,[10,3,1,5]]

,International Reputation,Nationality,Name,Potential
0,5.0,Argentina,L. Messi,94
1,5.0,Portugal,Cristiano Ronaldo,94
2,5.0,Brazil,Neymar Jr,93
3,4.0,Spain,De Gea,93
4,4.0,Belgium,K. De Bruyne,92
...,...,...,...,...
18200,1.0,Scotland,J. Young,62
18201,1.0,Republic of Ireland,D. Walsh,68
18202,1.0,England,J. Lundstram,65
18203,1.0,Sweden,N. Christoffersson,63
18204,1.0,England,B. Worman,67

In [ ]:
# create copy
new_df = df.copy()

In [ ]:
df.drop(columnS=["club","ID"])

TypeError: DataFrame.drop() got an unexpected keyword argument 'columnS'

In [ ]:
# check duplicate records count
df.duplicated().sum()

np.int64(0)

In [ ]:
# in this data we dont have duplicate data if their then we remove using drop
# df.drop duplicates()

In [ ]:
# we can also add data
import pandas as pd

df["New_Name"]="Prasad"
df

NameError: name 'df' is not defined

In [ ]:
# assignment
# add row
# Assignment:
# How to add a row in df
# How to append two dataframe
# How to concatanate two or more dataframe
# How to perform merge operation
# How to perform Join operations

In [ ]:
# How to add a row in df
# A new row can be added by using .loc[].

import pandas as pd


employees = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Prasad", "Rahul", "Amit", "Sneha", "Neha",
             "Rohan", "Priya", "Karan", "Pooja", "Anjali"],
    "Department": ["IT", "HR", "Sales", "Finance", "IT",
                   "Marketing", "HR", "Sales", "Finance", "IT"],
    "Salary": [50000, 45000, 40000, 55000, 60000,
               48000, 43000, 41000, 57000, 62000]
})

print(employees)

   Emp_ID    Name Department  Salary
0     101  Prasad         IT   50000
1     102   Rahul         HR   45000
2     103    Amit      Sales   40000
3     104   Sneha    Finance   55000
4     105    Neha         IT   60000
5     106   Rohan  Marketing   48000
6     107   Priya         HR   43000
7     108   Karan      Sales   41000
8     109   Pooja    Finance   57000
9     110  Anjali         IT   62000

In [ ]:
# How to add a row in df
# A new row can be added by using .loc[]..
employees.loc[len(employees)]=[111,'Amit',"Sales",50000]
print(employees)

    Emp_ID    Name Department  Salary
0      101  Prasad         IT   50000
1      102   Rahul         HR   45000
2      103    Amit      Sales   40000
3      104   Sneha    Finance   55000
4      105    Neha         IT   60000
5      106   Rohan  Marketing   48000
6      107   Priya         HR   43000
7      108   Karan      Sales   41000
8      109   Pooja    Finance   57000
9      110  Anjali         IT   62000
10     111    Amit      Sales   50000
11     111    Amit      Sales   50000

In [ ]:
# 2. How to Append Two DataFrames

import pandas as pd
df1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df2 = pd.DataFrame({'A': [4, 5, 6], 'B': [7, 8, 9]})
df3 = pd.concat([df1,df2])
print(df3)

   A  B
0  1  4
1  2  5
2  3  6
0  4  7
1  5  8
2  6  9

In [ ]:
# 3. How to Concatenate Two or More DataFrames
# Row wise concatenation
# column wise concatenation


# Row wise concatenation
import pandas as pd
df1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df2 = pd.DataFrame({'A': [4, 5, 6], 'B': [7, 8, 9]})
df3 = pd.concat([df1, df2],axis=0)
print(df3)

   A  B
0  1  4
1  2  5
2  3  6
0  4  7
1  5  8
2  6  9

In [ ]:
# column wise concatenation
import pandas as pd
df1 = pd.DataFrame({'A': [10, 20, 30], 'B': [40, 50, 60]})
df2 = pd.DataFrame({'C': [40, 50, 60], 'D': [70, 80, 90]})
df3 = pd.concat([df1, df2], axis=1)
print(df3)

    A   B   C   D
0  10  40  40  70
1  20  50  50  80
2  30  60  60  90

In [ ]:
# 4. How to Perform Merge Operation
# Merge is used to combine DataFrames using a common column


import pandas as pd
student = pd.DataFrame({
    "ID":[101,102,103],
    "Name":["Prasad","Rahul","Amit"]
})
marks = pd.DataFrame({
    "ID":[101,102,103],
    "Marks":[85,90,78]
})
result = pd.merge(student, marks, on="ID")
print(result)

    ID    Name  Marks
0  101  Prasad     85
1  102   Rahul     90
2  103    Amit     78

In [ ]:
# How to Perform Join Operations
import pandas as pd
df1 = pd.DataFrame({
    "Name":["Prasad","Rahul","Amit"]
}, index=[1,2,3])

df2 = pd.DataFrame({
    "Marks":[85,90,78]}, index=[1,2,4])

In [ ]:
# left join
result = df1.join(df2, how="left")
print(result)

     Name  Marks
1  Prasad   85.0
2   Rahul   90.0
3    Amit    NaN

In [ ]:
# right join
result= df1.join(df2,how="right")
print(result)

     Name  Marks
1  Prasad     85
2   Rahul     90
4     NaN     78

In [ ]:
# outer join
result = df1.join(df2,how="outer")
print(result)

     Name  Marks
1  Prasad   85.0
2   Rahul   90.0
3    Amit    NaN
4     NaN   78.0

In [ ]:
# Inner join
result = df1.join(df2,how = "inner")
print(result)

     Name  Marks
1  Prasad     85
2   Rahul     90