<a href="https://colab.research.google.com/github/prasad2154/NewVision/blob/main/Practice_Work/pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Assignment 1 on *Dmart*
# Q. Select item_name,qty
# Q. Select last 3 columns using loc and iloc
# Q. Display min,max,average price
# Q. Display 1st and last column
# Q. Select middle 3 columns and first 3 rows.
# Q. Select last 2 rows and all columns
# Q. Display total amount

In [ ]:
import pandas as pd
# create first D-Mart dataframe
data = {'id':[1,2,3,4,5],'item_name':['Rice 5kg Bag',
'Detergent Powder','Cooking Oil 1L', 'Biscuit Pack',
'Toothpaste'],'Price':[300,200,150,30,50],'Qty':[1,5,3,2,5],'Amount':[300,1000,450,60,250]}

In [ ]:
df=pd.DataFrame(data)
df

   id         item_name  Price  Qty  Amount
0   1      Rice 5kg Bag    300    1     300
1   2  Detergent Powder    200    5    1000
2   3    Cooking Oil 1L    150    3     450
3   4      Biscuit Pack     30    2      60
4   5        Toothpaste     50    5     250

In [ ]:
# Q. Select item_name,qty
df[['item_name','Qty']]

          item_name  Qty
0      Rice 5kg Bag    1
1  Detergent Powder    5
2    Cooking Oil 1L    3
3      Biscuit Pack    2
4        Toothpaste    5

In [ ]:
# Q. Select last 3 columns using loc and iloc
df.iloc[:,2:]

   Price  Qty  Amount
0    300    1     300
1    200    5    1000
2    150    3     450
3     30    2      60
4     50    5     250

In [ ]:
df.loc[:,['Price','Qty','Amount']]

   Price  Qty  Amount
0    300    1     300
1    200    5    1000
2    150    3     450
3     30    2      60
4     50    5     250

In [ ]:
# Q. Display min,max,average price
df['Price'].max()

300

In [ ]:
df['Price'].min()

30

In [ ]:
print(df['Price'].mean())

146.0

In [ ]:
# Display first and last column
df[['id',"Amount"]]  #method 1

   id  Amount
0   1     300
1   2    1000
2   3     450
3   4      60
4   5     250

In [ ]:
# method 2
df.iloc[:,::4]

   id  Amount
0   1     300
1   2    1000
2   3     450
3   4      60
4   5     250

In [ ]:
df

   id         item_name  Price  Qty  Amount
0   1      Rice 5kg Bag    300    1     300
1   2  Detergent Powder    200    5    1000
2   3    Cooking Oil 1L    150    3     450
3   4      Biscuit Pack     30    2      60
4   5        Toothpaste     50    5     250

In [ ]:
# Q. Select middle 3 columns and first 3 rows.

df.iloc[:3,1:4]

          item_name  Price  Qty
0      Rice 5kg Bag    300    1
1  Detergent Powder    200    5
2    Cooking Oil 1L    150    3

In [ ]:
# method 2
df.loc[:3,"item_name":"Qty"]

          item_name  Price  Qty
0      Rice 5kg Bag    300    1
1  Detergent Powder    200    5
2    Cooking Oil 1L    150    3
3      Biscuit Pack     30    2

In [ ]:
# Q. select last 2 rows and all columns
df.iloc[3:,:]

   id     item_name  Price  Qty  Amount
3   4  Biscuit Pack     30    2      60
4   5    Toothpaste     50    5     250

In [ ]:
# Method 2
df.loc[3:,'id':'Amount']

   id     item_name  Price  Qty  Amount
3   4  Biscuit Pack     30    2      60
4   5    Toothpaste     50    5     250

In [ ]:
# Display Total AmOUNT
df['Amount'].sum()

np.int64(2060)

Assignment 2
Create a DataFrame for a Library with at least 5 entries.

Columns: book_id | book_name | author | price | copies_sold

Q1. Select book_name and author.
Q2. Select the last 2 columns using loc and iloc.
Q3. Display the minimum, maximum, and average price of books.
Q4. Display the book_id|author|copies_sold
Q5. Select the middle 3 columns and the first 3 rows.
Q6. Select the last random 3 rows and all columns.
Q7. Display the total number of copies_sold.
Q8. Create a new column total_sales (calculated as price * copies_sold) and display the DataFrame.

In [ ]:


# Q1. Select book_name and author.
# Q2. Select the last 2 columns using loc and iloc.
# Q3. Display the minimum, maximum, and average price of books.
# Q4. Display the book_id|author|copies_sold
# Q5. Select the middle 3 columns and the first 3 rows.
# Q6. Select the last random 3 rows and all columns.
# Q7. Display the total number of copies_sold.
# # Q8. Create a new column total_sales (calculated as price * copies_sold) and display the DataFrame.

In [ ]:
data={'book_id':[11,12,13,14,15],'book_name':["The God of Small Things",
    "Midnight's Children",
    "The White Tiger",
    "A Suitable Boy",
    "Train to Pakistan"],'author':["Arundhati Roy",
    "Salman Rushdie",
    "Aravind Adiga",
    "Vikram Seth",
    "Khushwant Singh"],'Price':[499, 599, 399, 699, 350],'copies_sold':[1200000, 850000, 750000, 1000000, 600000]}

In [ ]:
df1=pd.DataFrame(data)
df1

   book_id                book_name           author  Price  copies_sold
0       11  The God of Small Things    Arundhati Roy    499      1200000
1       12      Midnight's Children   Salman Rushdie    599       850000
2       13          The White Tiger    Aravind Adiga    399       750000
3       14           A Suitable Boy      Vikram Seth    699      1000000
4       15        Train to Pakistan  Khushwant Singh    350       600000

In [ ]:
# Q1. Select book_name and author.
df1[['book_name','author']]

                 book_name           author
0  The God of Small Things    Arundhati Roy
1      Midnight's Children   Salman Rushdie
2          The White Tiger    Aravind Adiga
3           A Suitable Boy      Vikram Seth
4        Train to Pakistan  Khushwant Singh

In [ ]:
# Q2. Select the last 2 columns using loc and iloc.
df1.iloc[:,-2:]

   Price  copies_sold
0    499      1200000
1    599       850000
2    399       750000
3    699      1000000
4    350       600000

In [ ]:
df1.loc[:,'Price':'copies_sold']

   Price  copies_sold
0    499      1200000
1    599       850000
2    399       750000
3    699      1000000
4    350       600000

In [ ]:
# Q3. Display the minimum, maximum, and average price of books.
df1['Price'].max()

699

In [ ]:
# Min
df1['Price'].min()

350

In [ ]:
# Mean
print(df1['Price'].mean())

509.2

In [ ]:
# Q4. Display the book_id|author|copies_sold
df1[['book_id','author','copies_sold']]

   book_id           author  copies_sold
0       11    Arundhati Roy      1200000
1       12   Salman Rushdie       850000
2       13    Aravind Adiga       750000
3       14      Vikram Seth      1000000
4       15  Khushwant Singh       600000

In [ ]:
# Q5. Select the middle 3 columns and the first 3 rows.
df1.iloc[:3,1:4]

                 book_name          author  Price
0  The God of Small Things   Arundhati Roy    499
1      Midnight's Children  Salman Rushdie    599
2          The White Tiger   Aravind Adiga    399

In [ ]:
# Q6. Select the last random 3 rows and all columns
df1.iloc[2:,:]

   book_id          book_name           author  Price  copies_sold
2       13    The White Tiger    Aravind Adiga    399       750000
3       14     A Suitable Boy      Vikram Seth    699      1000000
4       15  Train to Pakistan  Khushwant Singh    350       600000

In [ ]:
# Q7. Display the total number of copies_sold.
print(df1['copies_sold'].sum())

4400000

In [ ]:
# Q8. Create a new column total_sales (calculated as price * copies_sold) and display the DataFrame.

df1['total_sales']=df1['Price']*df1['copies_sold']
df1

,book_id,book_name,author,Price,copies_sold,total_sales
0,11,The God of Small Things,Arundhati Roy,499,1200000,598800000
1,12,Midnight's Children,Salman Rushdie,599,850000,509150000
2,13,The White Tiger,Aravind Adiga,399,750000,299250000
3,14,A Suitable Boy,Vikram Seth,699,1000000,699000000
4,15,Train to Pakistan,Khushwant Singh,350,600000,210000000

In [5]:
import pandas as pd
path= "/content/HRMS_Dataset_2000_Employees.csv"
d = pd.read_csv(path)

In [ ]:
d.shape

(2000, 15)

In [ ]:
d.columns

Index(['Emp_ID', 'First_Name', 'Last_Name', 'Gender', 'Age', 'Department',
       'Designation', 'City', 'Email', 'Phone', 'Hire_Date',
       'Experience_Years', 'Salary', 'Performance_Rating',
       'Employment_Status'],
      dtype='object')

In [ ]:
d[["Emp_ID","First_Name","Last_Name","Salary"]]

       Emp_ID First_Name Last_Name  Salary
0     EMP0001      Priya     Patil  113696
1     EMP0002      Rohan    Shaikh  116506
2     EMP0003       Amit    Chavan   97357
3     EMP0004     Ananya  Kulkarni  112841
4     EMP0005      Rohan     Patel   33675
...       ...        ...       ...     ...
1995  EMP1996      Arjun    Jadhav   45994
1996  EMP1997      Meera  Deshmukh  114080
1997  EMP1998        Sai      More   91479
1998  EMP1999      Pooja  Deshmukh   26563
1999  EMP2000      Meera      More   79114

[2000 rows x 4 columns]

In [7]:
d.loc[:6,['First_Name', 'Last_Name', 'Gender', 'Age', 'Department']]

  First_Name Last_Name  Gender  Age  Department
0      Priya     Patil    Male   29          IT
1      Rohan    Shaikh  Female   21       Sales
2       Amit    Chavan    Male   45   Marketing
3     Ananya  Kulkarni  Female   43   Marketing
4      Rohan     Patel  Female   46  Operations
5      Nisha     Yadav  Female   35   Marketing
6     Vihaan    Chavan  Female   42   Marketing

In [8]:
d.iloc[:-3,[5,2,3]]

      Department Last_Name  Gender
0             IT     Patil    Male
1          Sales    Shaikh  Female
2      Marketing    Chavan    Male
3      Marketing  Kulkarni  Female
4     Operations     Patel  Female
...          ...       ...     ...
1992          IT     Yadav  Female
1993     Support     Verma    Male
1994       Sales  Deshmukh  Female
1995          IT    Jadhav    Male
1996   Marketing  Deshmukh    Male

[1997 rows x 3 columns]

In [10]:
d.duplicated().sum()

np.int64(0)

In [7]:
d.head()

,Emp_ID,First_Name,Last_Name,Gender,Age,Department,Designation,City,Email,Phone,Hire_Date,Experience_Years,Salary,Performance_Rating,Employment_Status
0,EMP0001,Priya,Patil,Male,29,IT,Software Engineer,Chennai,priya.patil1@company.com,9196001338,2019-02-24,3,113696,5,Active
1,EMP0002,Rohan,Shaikh,Female,21,Sales,Sales Manager,Nashik,rohan.shaikh2@company.com,9423511615,2019-10-16,0,116506,3,Resigned
2,EMP0003,Amit,Chavan,Male,45,Marketing,Marketing Executive,Delhi,amit.chavan3@company.com,9593103413,2018-11-19,22,97357,1,On Leave
3,EMP0004,Ananya,Kulkarni,Female,43,Marketing,SEO Specialist,Pune,ananya.kulkarni4@company.com,9928327648,2020-05-08,20,112841,2,Resigned
4,EMP0005,Rohan,Patel,Female,46,Operations,Operations Executive,Delhi,rohan.patel5@company.com,9537672423,2021-01-01,24,33675,5,Resigned

In [8]:
d['City'].unique()

array(['Chennai', 'Nashik', 'Delhi', 'Pune', 'Kolhapur', 'Mumbai',
       'Bengaluru', 'Sangli', 'Nagpur', 'Hyderabad'], dtype=object)

In [10]:
d['City'].nunique()

10

In [12]:
d.query("Department=='IT'")

,Emp_ID,First_Name,Last_Name,Gender,Age,Department,Designation,City,Email,Phone,Hire_Date,Experience_Years,Salary,Performance_Rating,Employment_Status
0,EMP0001,Priya,Patil,Male,29,IT,Software Engineer,Chennai,priya.patil1@company.com,9196001338,2019-02-24,3,113696,5,Active
15,EMP0016,Kavya,Deshmukh,Female,29,IT,Software Engineer,Nashik,kavya.deshmukh16@company.com,9427849808,2021-11-30,7,34016,3,Resigned
16,EMP0017,Priya,Gupta,Male,56,IT,Senior Developer,Delhi,priya.gupta17@company.com,9353487401,2019-09-29,33,60697,4,On Leave
22,EMP0023,Meera,Naik,Female,41,IT,QA Engineer,Chennai,meera.naik23@company.com,9236629946,2022-07-07,18,116384,5,Active
31,EMP0032,Amit,Reddy,Female,31,IT,Senior Developer,Pune,amit.reddy32@company.com,9241904966,2024-10-17,5,104593,2,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1977,EMP1978,Sneha,Khan,Male,42,IT,QA Engineer,Hyderabad,sneha.khan1978@company.com,9351851769,2019-05-11,19,86019,4,On Leave
1981,EMP1982,Isha,Deshmukh,Female,30,IT,Software Engineer,Delhi,isha.deshmukh1982@company.com,9229501496,2021-06-29,8,112972,2,Resigned
1992,EMP1993,Amit,Yadav,Female,34,IT,Software Engineer,Chennai,amit.yadav1993@company.com,9343871515,2019-12-15,11,63538,3,Resigned
1995,EMP1996,Arjun,Jadhav,Male,49,IT,Senior Developer,Kolhapur,arjun.jadhav1996@company.com,9021311679,2022-04-24,26,45994,3,Resigned
1998,EMP1999,Pooja,Deshmukh,Male,39,IT,Data Analyst,Sangli,pooja.deshmukh1999@company.com,9198410507,2025-07-22,16,26563,3,On Leave

In [18]:
d.query("Age == 29 and City == 'Delhi'")

,Emp_ID,First_Name,Last_Name,Gender,Age,Department,Designation,City,Email,Phone,Hire_Date,Experience_Years,Salary,Performance_Rating,Employment_Status
1236,EMP1237,Neha,Naik,Male,29,Admin,Office Executive,Delhi,neha.naik1237@company.com,9208235309,2021-04-30,6,26488,4,On Leave
1848,EMP1849,Aditya,Sharma,Male,29,HR,HR Manager,Delhi,aditya.sharma1849@company.com,9745371473,2019-03-22,4,77619,2,Active

In [20]:
d['Designation']== "FULL-SIZE"

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Name: Designation, Length: 2000, dtype: bool

In [21]:
list(d.groupby(["Age"]))

[((21,),
         Emp_ID First_Name Last_Name  Gender  Age  Department  \
  1     EMP0002      Rohan    Shaikh  Female   21       Sales
  68    EMP0069      Rohan     Yadav    Male   21   Marketing
  133   EMP0134     Vihaan     Singh  Female   21       Sales
  200   EMP0201     Sanjay      More    Male   21     Support
  261   EMP0262      Rohan      Khan  Female   21       Sales
  ...       ...        ...       ...     ...  ...         ...
  1796  EMP1797      Arjun  Deshmukh    Male   21       Admin
  1851  EMP1852       Amit      More    Male   21          HR
  1953  EMP1954       Amit     Yadav  Female   21   Marketing
  1956  EMP1957      Priya     Singh    Male   21  Operations
  1965  EMP1966      Kavya     Joshi  Female   21  Operations

                 Designation       City                           Email  \
  1            Sales Manager     Nashik       rohan.shaikh2@company.com
  68     Marketing Executive   Kolhapur       rohan.yadav69@company.com
  133          Sales Manager  Bengaluru     vihaan.singh134@company.com
  200       Support Engineer       Pune      sanjay.more201@company.com
  261        Sales Executive       Pune       rohan.khan262@company.com
  ...                    ...        ...                             ...
  1796      Office Executive       Pune  arjun.deshmukh1797@company.com
  1851          HR Executive  Bengaluru       amit.more1852@company.com
  1953   Marketing Executive    Chennai      amit.yadav1954@company.com
  1956    Operations Manager    Chennai     priya.singh1957@company.com
  1965  Operations Executive  Hyderabad     kavya.joshi1966@company.com

             Phone   Hire_Date  Experience_Years  Salary  Performance_Rating  \
  1     9423511615  2019-10-16                 0  116506                   3
  68    9445107622  2020-04-17                 0   64507                   4
  133   9575692459  2022-06-09                 0   68544                   2
  200   9972181143  2018-02-22                 0  113032                   4
  261   9630097925  2019-11-17                 0   61188                   1
  ...          ...         ...               ...     ...                 ...
  1796  9500111391  2025-08-15                 0   89226                   3
  1851  9870690571  2018-02-01                 0   71693                   1
  1953  9939116457  2021-04-30                 0   66372                   4
  1956  9506929873  2022-11-01                 0   35093                   5
  1965  9559841420  2020-08-20                 0   32032                   2

       Employment_Status
  1             Resigned
  68            Resigned
  133           On Leave
  200           On Leave
  261             Active
  ...                ...
  1796          On Leave
  1851            Active
  1953          On Leave
  1956          On Leave
  1965          On Leave

  [62 rows x 15 columns]),
 ((22,),
         Emp_ID First_Name Last_Name  Gender  Age  Department  \
  80    EMP0081      Rohan    Shaikh  Female   22       Admin
  101   EMP0102      Nisha      Naik  Female   22  Operations
  153   EMP0154     Aditya     Patil  Female   22       Sales
  188   EMP0189      Priya     Joshi  Female   22  Operations
  416   EMP0417      Priya     Joshi    Male   22          HR
  ...       ...        ...       ...     ...  ...         ...
  1918  EMP1919      Nisha    Sharma    Male   22          IT
  1925  EMP1926     Vihaan    Sharma  Female   22          IT
  1947  EMP1948       Isha     Patel    Male   22       Sales
  1987  EMP1988      Priya     Verma  Female   22     Finance
  1989  EMP1990     Aditya  Kulkarni    Male   22       Sales

                 Designation     City                            Email  \
  80           Administrator  Chennai       rohan.shaikh81@company.com
  101     Operations Manager     Pune        nisha.naik102@company.com
  153          Sales Manager  Chennai      aditya.patil154@company.com
  188   Operations Executive    Delhi       priya.joshi189@company.com
  416             HR Manager   Nagpur       priya.joshi417@company.com
  ...                    ...      ...                              ...
  1918     Software Engineer     Pune     nisha.sharma1919@company.com
  1925      Senior Developer   Nagpur    vihaan.sharma1926@company.com
  1947         Sales Manager   Sangli       isha.patel1948@company.com
  1987     Financial Analyst    Delhi      priya.verma1988@company.com
  1989       Sales Executive     Pune  aditya.kulkarni1990@company.com

             Phone   Hire_Date  Experience_Years  Salary  Performance_Rating  \
  80    9536153051  2022-08-27                 0   31980                   3
  101   9694097499  2022-02-17                 0   68416                   2
  153   9983640376  2025-05-20                 0   64537                   1
  188   9333346800  2022-05-03                 0   31507                   4
  416   9818139890  2024-05-31                 0  107589                   5
  ...          ...         ...               ...     ...                 ...
  1918  9369300522  2022-04-03                 0   26517                   1
  1925  9539601609  2023-04-01                 0   45599                   5
  1947  9653298568  2020-04-08                 1   60214                   3
  1987  9518695613  2020-10-03                 0  114152                   3
  1989  9852002391  2018-11-11                 0   75535                   3

       Employment_Status
  80              Active
  101           Resigned
  153             Active
  188             Active
  416           Resigned
  ...                ...
  1918          Resigned
  1925            Active
  1947          Resigned
  1987          On Leave
  1989            Active

  [61 rows x 15 columns]),
 ((23,),
         Emp_ID First_Name Last_Name  Gender  Age  Department  \
  18    EMP0019     Vivaan      Naik  Female   23       Admin
  24    EMP0025      Rahul     Singh    Male   23   Marketing
  88    EMP0089      Arjun     Verma  Female   23     Finance
  126   EMP0127      Rohan      Naik    Male   23     Support
  184   EMP0185      Nisha     Verma  Female   23       Admin
  201   EMP0202     Vivaan     Gupta    Male   23   Marketing
  217   EMP0218      Rohan     Verma    Male   23  Operations
  228   EMP0229       Neha     Pawar  Female   23       Sales
  234   EMP0235      Meera      Khan  Female   23          HR
  368   EMP0369        Sai    Sharma  Female   23          IT
  394   EMP0395      Nisha     Patel    Male   23       Admin
  395   EMP0396        Sai  Kulkarni  Female   23          IT
  399   EMP0400      Karan     Pawar  Female   23          IT
  444   EMP0445     Vihaan     Joshi  Female   23       Sales
  530   EMP0531      Sneha    Jadhav  Female   23     Finance
  614   EMP0615      Meera     Joshi  Female   23   Marketing
  654   EMP0655       Amit      More  Female   23       Admin
  809   EMP0810      Meera     Pawar    Male   23       Admin
  929   EMP0930        Sai     Patel    Male   23          IT
  981   EMP0982     Aditya      More    Male   23       Admin
  1007  EMP1008     Vihaan     Joshi    Male   23   Marketing
  1046  EMP1047      Rohan     Gupta    Male   23  Operations
  1048  EMP1049       Neha    Jadhav  Female   23       Admin
  1103  EMP1104      Priya      Naik    Male   23     Support
  1115  EMP1116      Kavya     Gupta    Male   23          HR
  1147  EMP1148      Arjun     Yadav    Male   23   Marketing
  1249  EMP1250     Vihaan     Verma  Female   23     Finance
  1272  EMP1273       Isha    Sawant  Female   23          IT
  1297  EMP1298     Vivaan      More  Female   23  Operations
  1335  EMP1336      Kavya     Patel    Male   23          IT
  1353  EMP1354      Priya    Jadhav  Female   23       Sales
  1393  EMP1394      Pooja     Patel    Male   23          IT
  1409  EMP1410      Aarav     Joshi  Female   23     Finance
  1432  EMP1433      Rohan      Khan    Male   23          IT
  1449  EMP1450      Priya    Mishra    Male   23     Support
  1503  EMP1504      Rohan    Jadhav    Male   23       Sales
  1554  EMP1555      Rohan     Joshi  Female   23     Finance
  1639  EMP1640     Ananya     Verma    Male   23  Operations
  1651  EMP1652       Amit     Patel    Male   23  Operations
  1791  EMP1792       Neha     Yadav  Female   23     Finance
  1799  EMP1800      Nisha     Yadav    Male   23     Finance
  1854  EMP1855      Nisha    Sharma    Male   23  Operations
  1856  EMP1857      Rohan    Shaikh  Female   23       Admin
  1921  EMP1922       Isha    Mishra  Female   23          IT
  1944  EMP1945       Amit    Sharma  Female   23          HR
  1978  EMP1979      Pooja      Khan    Male   23  Operations

                 Designation       City                         Email  \
  18           Administrator     Sangli     vivaan.naik19@company.com
  24     Marketing Executive       Pune     rahul.singh25@company.com
  88              Accountant     Nashik     arjun.verma89@company.com
  126       Support Engineer  Bengaluru     rohan.naik127@company.com
  184       Office Executive   Kolhapur    nisha.verma185@company.com
  201         SEO Specialist     Nashik   vivaan.gupta202@company.com
  217     Operations Manager       Pune    rohan.verma218@company.com
  228          Sales Manager       Pune     neha.pawar229@company.com
  234             HR Manager     Sangli     meera.khan235@company.com
  368            QA Engineer      Delhi     sai.sharma369@company.com
  394       Office Executive  Bengaluru    nisha.patel395@company.com
  395           Data Analyst     Nagpur   sai.kulkarni396@company.com
  399           Data Analyst    Chennai    karan.pawar400@company.com
  444        Sales Executive     Sangli   vihaan.joshi445@company.com
  530      Financial Analyst     Sangli   sneha.jadhav531@company.com
  614         SEO Specialist    Chennai    meera.joshi615@company.com
  654          Administrator     Mumbai      amit.more655@company.com
  809          Administrator     Nashik    meera.pawar810@company.com
  929       Senior Developer     Nashik      sai.patel930@company.com
  981       Office Executive  Bengaluru    aditya.more982@company.com
  1007        SEO Specialist  Bengaluru  vihaan.joshi1008@company.com
  1046  Operations Executive       Pune   rohan.gupta1047@company.com
  1048         Administrator     Mumbai   neha.jadhav1049@company.com
  1103      Support Engineer    Chennai    priya.naik1104@company.com
  1115            HR Manager   Kolhapur   kavya.gupta1116@company.com
  1147   Marketing Executive       Pune   arjun.yadav1148@company.com
  1249            Accountant   Kolhapur  vihaan.verma1250@company.com
  1272           QA Engineer     Nashik   isha.sawant1273@company.com
  1297    Operations Manager       Pune   vivaan.more1298@company.com
  1335          Data Analyst       Pune   kavya.patel1336@company.com
  1353         Sales Manager   Kolhapur  priya.jadhav1354@company.com
  1393     Software Engineer   Kolhapur   pooja.patel1394@company.com
  1409     Financial Analyst      Delhi   aarav.joshi1410@company.com
  1432      Senior Developer   Kolhapur    rohan.khan1433@company.com
  1449      Customer Support     Mumbai  priya.mishra1450@company.com
  1503       Sales Executive     Nashik  rohan.jadhav1504@company.com
  1554            Accountant     Nashik   rohan.joshi1555@company.com
  1639    Operations Manager  Bengaluru  ananya.verma1640@company.com
  1651    Operations Manager  Hyderabad    amit.patel1652@company.com
  1791            Accountant     Sangli    neha.yadav1792@company.com
  1799            Accountant   Kolhapur   nisha.yadav1800@company.com
  1854  Operations Executive       Pune  nisha.sharma1855@company.com
  1856      Office Executive       Pune  rohan.shaikh1857@company.com
  1921           QA Engineer     Sangli   isha.mishra1922@company.com
  1944            HR Manager     Sangli   amit.sharma1945@company.com
  1978    Operations Manager     Sangli    pooja.khan1979@company.com

             Phone   Hire_Date  Experience_Years  Salary  Performance_Rating  \
  18    9158692322  2022-01-05                 0   52535                   4
  24    9769367632  2020-09-29                 0   87277                   1
  88    9569092755  2019-06-02                 1   33812                   4
  126   9870021765  2019-01-18                 0   78120                   5
  184   9996065307  2019-12-07                 0   61099                   3
  201   9611002255  2021-04-05                 0   72214                   4
  217   9648408588  2025-08-27                 0   67065                   4
  228   9844989266  2018-06-13                 0  110003                   3
  234   9765991624  2025-10-28                 0   94444                   4
  368   9864079056  2023-03-03                 0  111214                   5
  394   9617945491  2023-10-04                 0   39107                   5
  395   9597794523  2018-12-08                 0   79558                   2
  399   9997308069  2023-06-20                 0   77386                   3
  444   9544439284  2024-02-15                 0   51254                   1
  530   9399129710  2025-12-29                 0  114505                   2
  614   9538003296  2022-11-11                 0   38164                   2
  654   9863218122  2024-09-06                 0   39638                   4
  809   9419666450  2020-04-27                 0   34622                   3
  929   9873393049  2023-01-03                 0   42824                   2
  981   9641106541  2022-11-21                 0   81734                   1
  1007  9053088684  2024-05-29                 0   30221                   2
  1046  9505764497  2019-10-12                 0   40866                   3
  1048  9635537309  2020-11-18                 2   68335                   4
  1103  9803318361  2021-09-27                 0   55325                   1
  1115  9437361587  2021-03-06                 2   67957                   2
  1147  9745273536  2023-12-15                 0   70436                   3
  1249  9205397077  2021-04-24                 0   84614                   3
  1272  9049326643  2024-08-10                 0  106293                   2
  1297  9879938444  2022-01-04                 0   41643                   1
  1335  9348548420  2020-10-06                 1   63270                   2
  1353  9761368149  2018-12-06                 0   77307                   5
  1393  9600802658  2018-10-11                 0   77031                   5
  1409  9069522233  2023-07-14                 1   61075                   4
  1432  9721051334  2018-11-06                 0   56927                   4
  1449  9372954585  2021-06-25                 0  115340                   5
  1503  9684676780  2022-11-25                 0   91840                   5
  1554  9866399287  2019-01-17                 0  106452                   5
  1639  9757799113  2021-08-28                 0   71219                   4
  1651  9413644594  2018-06-17                 2   78880                   4
  1791  9123443584  2021-01-23                 0   96182                   5
  1799  9643205869  2020-01-13                 0   50384                   5
  1854  9548805109  2021-06-01                 0   34020                   2
  1856  9704701259  2025-03-05                 1  109772                   2
  1921  9585935803  2020-01-20                 1   50100                   3
  1944  9651875692  2023-05-31                 0  107348                   4
  1978  9752296484  2025-03-08                 0   54971                   2

       Employment_Status
  18              Active
  24              Active
  88              Active
  126             Active
  184           On Leave
  201           Resigned
  217           On Leave
  228           Resigned
  234             Active
  368           On Leave
  394             Active
  395             Active
  399           Resigned
  444           On Leave
  530           On Leave
  614           Resigned
  654           On Leave
  809           On Leave
  929           On Leave
  981           Resigned
  1007            Active
  1046          On Leave
  1048          On Leave
  1103          Resigned
  1115          On Leave
  1147            Active
  1249          On Leave
  1272            Active
  1297          On Leave
  1335          On Leave
  1353            Active
  1393          Resigned
  1409          Resigned
  1432            Active
  1449            Active
  1503          On Leave
  1554          Resigned
  1639          Resigned
  1651          On Leave
  1791          Resigned
  1799          On Leave
  1854            Active
  1856          Resigned
  1921          Resigned
  1944          Resigned
  1978            Active  ),
 ((24,),
         Emp_ID First_Name Last_Name  Gender  Age  Department  \
  25    EMP0026        Sai    Sawant  Female   24       Admin
  178   EMP0179      Sneha     Patil    Male   24   Marketing
  219   EMP0220     Vivaan     Joshi    Male   24     Support
  231   EMP0232      Meera     Patel    Male   24     Finance
  259   EMP0260      Pooja     Joshi    Male   24     Support
  262   EMP0263     Aditya     Verma  Female   24     Finance
  291   EMP0292       Isha    Chavan    Male   24       Sales
  327   EMP0328      Arjun    Sharma    Male   24          HR
  431   EMP0432      Pooja     Joshi    Male   24          HR
  472   EMP0473     Sanjay     Gupta    Male   24       Sales
  492   EMP0493      Kavya     Reddy    Male   24  Operations
  493   EMP0494      Arjun     Yadav  Female   24     Finance
  564   EMP0565      Meera      Khan    Male   24   Marketing
  697   EMP0698      Nisha     Patel  Female   24  Operations
  725   EMP0726      Sneha     Pawar  Female   24     Support
  733   EMP0734      Arjun    Chavan  Female   24   Marketing
  825   EMP0826      Rahul    Jadhav    Male   24     Finance
  840   EMP0841     Aditya      More  Female   24   Marketing
  846   EMP0847       Amit  Kulkarni    Male   24          HR
  927   EMP0928     Sanjay     Reddy    Male   24   Marketing
  950   EMP0951       Amit     Yadav  Female   24       Admin
  979   EMP0980       Neha     Joshi  Female   24       Sales
  1082  EMP1083       Isha  Kulkarni    Male   24     Finance
  1146  EMP1147      Karan    Shaikh    Male   24   Marketing
  1202  EMP1203      Rohan     Verma    Male   24          HR
  1223  EMP1224      Sneha     Patel  Female   24     Finance
  1257  EMP1258     Vihaan     Pawar  Female   24  Operations
  1260  EMP1261       Amit    Mishra  Female   24  Operations
  1275  EMP1276      Rahul    Shaikh  Female   24     Finance
  1277  EMP1278      Rahul     Yadav    Male   24     Support
  1314  EMP1315      Meera    Jadhav    Male   24       Sales
  1317  EMP1318     Vivaan  Kulkarni    Male   24       Admin
  1375  EMP1376      Rahul    Shaikh    Male   24     Finance
  1443  EMP1444     Aditya     Patel  Female   24       Sales
  1455  EMP1456      Priya     Gupta    Male   24     Finance
  1473  EMP1474      Karan     Joshi  Female   24  Operations
  1615  EMP1616     Vivaan     Joshi    Male   24          HR
  1636  EMP1637      Rohan    Jadhav  Female   24     Support
  1711  EMP1712      Rohan  Deshmukh  Female   24       Sales
  1721  EMP1722      Meera     Patil  Female   24       Sales
  1736  EMP1737      Pooja     Singh    Male   24       Sales
  1820  EMP1821       Neha    Sawant    Male   24     Finance
  1825  EMP1826      Pooja    Sawant    Male   24       Sales
  1879  EMP1880      Nisha    Sawant    Male   24          HR
  1909  EMP1910       Amit    Sharma    Male   24  Operations
  1934  EMP1935      Rohan    Sharma  Female   24          IT
  1975  EMP1976      Aarav     Patel    Male   24       Sales

                 Designation       City                            Email  \
  25           Administrator  Hyderabad         sai.sawant26@company.com
  178         SEO Specialist  Hyderabad       sneha.patil179@company.com

In [24]:
d.rename(columns={"Emp_ID":"Employee_ID"})

,Employee_ID,First_Name,Last_Name,Gender,Age,Department,Designation,City,Email,Phone,Hire_Date,Experience_Years,Salary,Performance_Rating,Employment_Status
0,EMP0001,Priya,Patil,Male,29,IT,Software Engineer,Chennai,priya.patil1@company.com,9196001338,2019-02-24,3,113696,5,Active
1,EMP0002,Rohan,Shaikh,Female,21,Sales,Sales Manager,Nashik,rohan.shaikh2@company.com,9423511615,2019-10-16,0,116506,3,Resigned
2,EMP0003,Amit,Chavan,Male,45,Marketing,Marketing Executive,Delhi,amit.chavan3@company.com,9593103413,2018-11-19,22,97357,1,On Leave
3,EMP0004,Ananya,Kulkarni,Female,43,Marketing,SEO Specialist,Pune,ananya.kulkarni4@company.com,9928327648,2020-05-08,20,112841,2,Resigned
4,EMP0005,Rohan,Patel,Female,46,Operations,Operations Executive,Delhi,rohan.patel5@company.com,9537672423,2021-01-01,24,33675,5,Resigned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,EMP1996,Arjun,Jadhav,Male,49,IT,Senior Developer,Kolhapur,arjun.jadhav1996@company.com,9021311679,2022-04-24,26,45994,3,Resigned
1996,EMP1997,Meera,Deshmukh,Male,45,Marketing,Marketing Executive,Pune,meera.deshmukh1997@company.com,9167811678,2023-07-17,24,114080,4,Resigned
1997,EMP1998,Sai,More,Male,42,Finance,Accountant,Nagpur,sai.more1998@company.com,9267302209,2020-02-13,18,91479,5,On Leave
1998,EMP1999,Pooja,Deshmukh,Male,39,IT,Data Analyst,Sangli,pooja.deshmukh1999@company.com,9198410507,2025-07-22,16,26563,3,On Leave
1999,EMP2000,Meera,More,Male,56,HR,HR Manager,Hyderabad,meera.more2000@company.com,9037846797,2021-04-07,32,79114,1,Resigned

In [25]:
d.select_dtypes(include=[float,int])

      Age       Phone  Experience_Years  Salary  Performance_Rating
0      29  9196001338                 3  113696                   5
1      21  9423511615                 0  116506                   3
2      45  9593103413                22   97357                   1
3      43  9928327648                20  112841                   2
4      46  9537672423                24   33675                   5
...   ...         ...               ...     ...                 ...
1995   49  9021311679                26   45994                   3
1996   45  9167811678                24  114080                   4
1997   42  9267302209                18   91479                   5
1998   39  9198410507                16   26563                   3
1999   56  9037846797                32   79114                   1

[2000 rows x 5 columns]

In [26]:
d.select_dtypes(include=["number"])

      Age       Phone  Experience_Years  Salary  Performance_Rating
0      29  9196001338                 3  113696                   5
1      21  9423511615                 0  116506                   3
2      45  9593103413                22   97357                   1
3      43  9928327648                20  112841                   2
4      46  9537672423                24   33675                   5
...   ...         ...               ...     ...                 ...
1995   49  9021311679                26   45994                   3
1996   45  9167811678                24  114080                   4
1997   42  9267302209                18   91479                   5
1998   39  9198410507                16   26563                   3
1999   56  9037846797                32   79114                   1

[2000 rows x 5 columns]